name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install cpp
      run: |
        sudo apt-get update
        sudo apt install g++
    - name: Install FLTK
      run: |
        sudo apt-get install libfltk1.3-dev
        sudo apt-get install libx11-dev
    - name: Compile
      run: make
    - name: Start
      run: Game
